stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.3-openjdk-11
      shellScript: mvn package -DskipTests -Djava.util.logging.config.file=vertx-default-jul-logging.properties
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: folioci/mod-source-record-manager:spitfire-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: folioci
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-4qb6b:spitfire-helmcharts-mod-source-record-manager
      version: 0.1.32
      answers:
        image.repository: folioci/mod-source-record-manager
        image.tag: spitfire-${CICD_EXECUTION_SEQUENCE}
      targetNamespace: spitfire
      name: mod-source-record-manager
timeout: 60
notification: {}
