#%RAML 1.0

title: Change Manager
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Change Manager API
    content: API for accessing ChangeManager's bussiness logic

types:
  jobExecution: !include raml-storage/schemas/mod-source-record-manager/jobExecution.json
  fileDto: !include raml-storage/schemas/dto/fileDto.json
  initJobExecutionsRqDto: !include raml-storage/schemas/dto/initJobExecutionsRqDto.json
  initJobExecutionsRsDto: !include raml-storage/schemas/dto/initJobExecutionsRsDto.json
  rawRecordsDto: !include raml-storage/schemas/dto/rawRecordsDto.json
  errors: !include raml-storage/raml-util/schemas/errors.schema

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml

/change-manager:
  /jobExecutions:
    post:
      description: "Initialize JobExecutions"
      body:
        application/json:
          schema: initJobExecutionsRqDto
      responses:
        201:
          body:
            application/json:
              schema: initJobExecutionsRsDto
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /jobExecution/{id}:
    put:
      description: "Update JobExecution"
      body:
        application/json:
          schema: jobExecution
      responses:
        200:
          body:
            application/json:
              type: jobExecution
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Not found"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    get:
      description: Get JobExecution by id
      responses:
        200:
          body:
            application/json:
              type: jobExecution
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Not found"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /records/{jobExecutionId}:
    post:
      description: "Receive chunk of raw records"
      body:
        application/json:
          schema: rawRecordsDto
      responses:
        204:
          body:
            text/plain: !!null
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Not found"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
