#%RAML 1.0

title: Metadata Provider
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Metadata Provider API
    content: API for accessing metadata

types:
  jobExecution: !include raml-storage/schemas/mod-source-record-manager/jobExecution.json
  jobExecutionDto: !include raml-storage/schemas/dto/jobExecutionDto.json
  jobExecutionDtoCollection: !include raml-storage/schemas/dto/jobExecutionDtoCollection.json
  edifactParsedContent: !include raml-storage/schemas/dto/edifactParsedContent.json
  errors: !include raml-storage/raml-util/schemas/errors.schema
  jobExecutionSourceChunk: !include raml-storage/schemas/mod-source-record-manager/jobExecutionSourceChunk.json
  jobExecutionLogDto: !include raml-storage/schemas/dto/jobExecutionLogDto.json
  journalRecordCollection: !include raml-storage/schemas/mod-source-record-manager/journalRecordCollection.json
  jobLogEntryDto: !include raml-storage/schemas/dto/jobLogEntryDto.json
  jobLogEntryDtoCollection: !include raml-storage/schemas/dto/jobLogEntryDtoCollection.json
  recordProcessingLogDto: !include raml-storage/schemas/dto/recordProcessingLogDto.json

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml
  searchable: !include raml-storage/raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-storage/raml-util/rtypes/collection.raml
  collection-item: !include raml-storage/raml-util/rtypes/item-collection.raml

/metadata-provider:
  /jobExecutions:
    get:
      is: [
        pageable
      ]
      queryParameters:
        statusAny:
          description: JobExecution statuses to filter by
          type: string[]
          example: [COMMITTED, ERROR]
          required: false
        profileIdNotAny:
          description: Filter by specified job profile ids
          type: string[]
          example: ["d0ebb7b0-2f0f-11eb-adc1-0242ac120002", "91f9b8d6-d80e-4727-9783-73fb53e3c786"]
          required: false
        statusNot:
          description: Filter by status not equal to
          type: string
          example: COMPLETED
          required: false
        uiStatusAny:
          description: JobExecution statuses to filter by
          type: string[]
          example: ["READY_FOR_PREVIEW"]
          required: false
        hrId:
          description: Filter by jobExecution hrid
          type: string
          example: "123"
          required: false
        fileName:
          description: Filter by jobExecution file name
          type: string
          example: importBib1.bib
          required: false
        profileIdAny:
          description: Filter by specified job profile ids
          type: string[]
          example: ["d0ebb7b0-2f0f-11eb-adc1-0242ac120002", "91f9b8d6-d80e-4727-9783-73fb53e3c786"]
          required: false
        userId:
          description: Filter by user id
          type: string
          example: d0ebb7b0-2f0f-11eb-adc1-0242ac120002
          required: false
        completedAfter:
          description: Start date to filter after, inclusive
          type: datetime
          required: false
        completedBefore:
          description: End date to filter before, inclusive
          type: datetime
          required: false
        sortBy:
          description: "sorting jobExecutions by field: completed_date, progress_total, file_name, status, job_profile_name, hrid"
          example: completed_date
          type: string
          required: false
          default: completed_date
        order:
          description: "sorting direction"
          example: desc
          enum: [asc, desc]
          required: false
          default: asc
      responses:
        200:
          body:
            application/json:
              schema: jobExecutionDtoCollection
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /logs/{jobExecutionId}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: jobExecutionLogDto
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /journalRecords/{jobExecutionId}:
    get:
      description: get journal records by job execution id
      queryParameters:
        sortBy:
          description: sort criteria
          example: "source_record_order, action_type, error"
          type: string
          required: false
        order:
          description: sort direction
          example: desc
          enum: [asc, desc]
          default: asc
      responses:
        200:
          body:
            application/json:
              schema: journalRecordCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Not found"
  /jobLogEntries/{jobExecutionId}:
    get:
      is: [pageable]
      description: get journal records by job execution id
      queryParameters:
        sortBy:
          description: "sorting by field: source_record_order, title, source_record_action_status, instance_action_status, holdings_action_status, item_action_status, order_action_status, invoice_action_status, error"
          example: source_record_order
          type: string
          required: false
          default: source_record_order
        order:
          description: "sorting direction"
          example: desc
          enum: [asc, desc]
          required: false
          default: asc
      responses:
        200:
          body:
            application/json:
              schema: jobLogEntryDtoCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
  /jobLogEntries/{jobExecutionId}/records/{recordId}:
    get:
      description: get record processing log dto by job execution id and record id (to get EDIFACT import log data a journal record id is expected)
      responses:
        200:
          body:
            application/json:
              schema: recordProcessingLogDto
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Not found"
